// Code generated by protoc-gen-go.
// source: msg.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	HelloReq
	HelloAck
	DelayNtf
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// msg=1
type HelloReq struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloReq) Reset()                    { *m = HelloReq{} }
func (m *HelloReq) String() string            { return proto.CompactTextString(m) }
func (*HelloReq) ProtoMessage()               {}
func (*HelloReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// msg=2
type HelloAck struct {
	Content string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
}

func (m *HelloAck) Reset()                    { *m = HelloAck{} }
func (m *HelloAck) String() string            { return proto.CompactTextString(m) }
func (*HelloAck) ProtoMessage()               {}
func (*HelloAck) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloAck) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// msg=3
type DelayNtf struct {
	Ts string `protobuf:"bytes,1,opt,name=ts" json:"ts,omitempty"`
}

func (m *DelayNtf) Reset()                    { *m = DelayNtf{} }
func (m *DelayNtf) String() string            { return proto.CompactTextString(m) }
func (*DelayNtf) ProtoMessage()               {}
func (*DelayNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *DelayNtf) GetTs() string {
	if m != nil {
		return m.Ts
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloReq)(nil), "pb.HelloReq")
	proto.RegisterType((*HelloAck)(nil), "pb.HelloAck")
	proto.RegisterType((*DelayNtf)(nil), "pb.DelayNtf")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 125 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x92, 0xe3, 0xe2, 0xf0, 0x48, 0xcd,
	0xc9, 0xc9, 0x0f, 0x4a, 0x2d, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x54, 0xa0, 0xf2, 0x8e, 0xc9, 0xd9, 0x42, 0x12, 0x5c,
	0xec, 0xc9, 0xf9, 0x79, 0x25, 0xa9, 0x79, 0x25, 0x50, 0x25, 0x30, 0xae, 0x92, 0x14, 0x17, 0x87,
	0x4b, 0x6a, 0x4e, 0x62, 0xa5, 0x5f, 0x49, 0x9a, 0x10, 0x1f, 0x17, 0x53, 0x49, 0x31, 0x54, 0x01,
	0x53, 0x49, 0xb1, 0x13, 0xeb, 0x2a, 0x26, 0xa6, 0x80, 0xa4, 0x24, 0x36, 0xb0, 0x9d, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x30, 0x5b, 0xa5, 0xe1, 0x80, 0x00, 0x00, 0x00,
}
